### ISSUE TITLE
Static Tags

### ISSUE THREAD

**Issue by Westermann** [getsentry/airflow-metrics#43]
It would be nice if it was possible to add static tags (e.g. for that airflow deployment) through the connection that are sent with all metrics. E.g. configure the connection as follows:
```
{
  "api_key": "XXXX...XXX",
  "tags": {
    "environment": "staging",
    "deployment": "company-a"
  }
}
```
and then those tags get sent with every metric.

**Comment by mikeclarke** [comment]
@Westermann great suggestion, thanks. Do you have thoughts on how these might be configured, maybe via airflow.cfg?

**Comment by Westermann** [comment]
In the above example I was thinking mostly about configuring it from the UI but if you don't use it then I suppose just a _JSON_ in the the `airflow.cfg` should do, no?
